version: '2'
services:
  nginx:
      build: ./nginx
      privileged: true
      ports:
        - "80:80"
        - "443:443"
      links:
        - "php71"
        - "php56"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./vhost/:/etc/nginx/conf.d/
        - ./www/:/var/www/
        - ./logs/nginx/:/var/log/nginx/

  php71:
      build:
        context: ./php71
        dockerfile: Dockerfile
        args:
          - INSTALL_XDEBUG=true
      privileged: true
      ports:
        - "9071:9000"
      links:
        - "mysql"
        - "redis"
      volumes:
        - ./www/:/var/www/
        - ./php71/php.ini:/usr/local/etc/php/php.ini
        - ./php71/php-fpm.conf:/usr/local/etc/php-fpm.conf
        - ./php71/ext:/usr/local/lib/ext
        - ./logs/php/xdebug/:/tmp/

  php56:
      build: ./php56
      privileged: true
      ports:
        - "9056:9000"
      links:
        - "mysql"
        - "mongo"
      volumes:
        - ./www/:/var/www/
        - ./php56/php.ini:/usr/local/etc/php/php.ini
        - ./php56/php-fpm.conf:/usr/local/etc/php-fpm.conf

  mysql:
      build: ./mysql
      privileged: true
      ports:
        - "3306:3306"
      volumes:
        - ./data/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: kfkdock

  redis:
      build: ./redis
      privileged: true
      ports:
        - "6379:6379"

  mongo:
      build: ./mongo
      privileged: true
      ports:
        - "27017:27017"
      volumes:
        - ./data/mongo:/data/db